### ISSUE TITLE
Provide a command line interface to guess the cpe from a software/product name

### ISSUE THREAD

**Issue by adulau** [cve-search/cpe-guesser#1]
Provide a command line interface to guess the cpe from a software/product name. CPEs are not always available from vendors and there is a manual work to find the correct CPE. The idea is to provide a small software to guess the most probable CPE out of a vendor/product string.

- Some ideas: https://github.com/fkie-cad/iva/tree/master/matching

**Comment by adulau** [comment]
First super alpha version. Released. 

- [ ] Add a public server instance
- [ ] Include the interface in cve-search and CveXplore to ease search

**Comment by P-T-I** [comment]
I'll take the action to include the interface in CveXplore

**Comment by P-T-I** [comment]
@adulau is this repo moving towards the NIST API as well?

**Comment by adulau** [comment]
Yep indeed. I hope they will the CPE available and updated (especially with the current state of the NVD part).

**Comment by adulau** [comment]
Command line implemented sometime ago https://github.com/cve-search/cpe-guesser/blob/main/bin/lookup.py
